# Generated by Django 4.1 on 2023-04-21 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
