# Generated by Django 4.1 on 2023-04-21 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0003_remove_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="author",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
