# Generated by Django 4.1 on 2023-04-21 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0004_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
