# Generated by Django 4.1 on 2023-04-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0005_userprofile_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
