# Generated by Django 4.1 on 2023-04-22 08:44

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.movie_image_file_path
            ),
        ),
    ]
